name: Test, Build & Deploy

on:
  # Runs when a pull request targeting the default branch is made.
  pull_request:
    branches: ['main']
  # Runs when commits are pushed targeting the default branch.
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Linting & tests
  check-code:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository, so your workflow can access it.
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js for linting files.
      # https://github.com/actions/setup-node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Keep updated with .nvmrc

      # Get cached & install node dependencies.
      # https://github.com/actions/cache
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v3-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v3-npm-deps-
      - name: Install node dependencies
        run: npm ci --no-optional --no-audit --progress=false

      # Run linters.
      - name: Lint - Formatting
        run: npm run lint:format

  # Build the files and deploy to Pages
  build-and-deploy:
    # Only allow one instance of this workflow to run at a time per branch
    # to prevent double deployments
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: ['check-code']
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository, so your workflow can access it.
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # This project is built using npm and outputs the result to the 'site' folder.
      # - name: Install and Build
      #   run: |
      #     npm ci
      #     npm run build

      # Automatically deploy your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The folder the action should deploy.
          folder: site
          # (Do not) Force-push new deployments to overwrite the previous version
          force: false
