name: Test, Build & Deploy

on:
  # Runs when commits are pushed targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository, so your workflow can access it.
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # This project is built using npm and outputs the result to the 'site' folder.
      # - name: Install and Build
      #   run: |
      #     npm ci
      #     npm run build

      # Automatically deploy your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The folder the action should deploy.
          folder: site
          # (Do not) Force-push new deployments to overwrite the previous version
          force: false
